### PR TITLE
Please push

### PR DESCRIPTION
**Pull request by Wenleiyu**

### CODE REVIEW

**Comment by choernem** [comment]
I get an error with how you added "Hello World!". I don't think you can concatenate a string with the contents of a reference in that way.

**Comment by Wenleiyu** [comment]
No, we can’t. I just did it to see can I see the change on GitHub or not, I
didn’t check the syntax.

**Comment by choernem** [comment]
Gotcha. Makes sense.

**Comment by choernem** [comment]
Why did you merge the Skip_Question with improveGreeting?

**Comment by Wenleiyu** [comment]
I think I merged it earlier cuz we thought merge two branches and then
changed the code.

**Comment by choernem** [comment]
Fix Skip alignment and make back button functional on Cheat

**Pull request merged**
